applications/persona/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name="persona_app"

urlpatterns = [
    path(
        '', 
        views.InicioView.as_view(),
        name='inicio'
    ),
    path(
        'listar-todo-empleados/', 
        views.ListAllEmpleados.as_view(),
        name='empleados_all'
    ),
    path(
        'lista-by-area/<shorname>/', 
        views.ListByAreaEmpleado.as_view(),
        name='empleados_area'
    ),
    path(
        'lista-empleados-admin/', 
        views.ListEmpleadosAdmin.as_view(),
        name='empleados_admin'
    ),
    path(
        'buscar-empleado/', 
        views.ListEmpleadoByKword.as_view(),
        name='lista_by_area'
    ),
    path(
        'lista-habilidades-empleado/', 
        views.ListHabilidadesEmpleado.as_view(),
        name='lista_habilidades_empleado'
    ),
    path(
        'ver-empleado/<pk>/', 
        views.EmpleadoDetailView.as_view(),
        name='empleado_detail'
    ),
    path(
        'add-empleado/', 
        views.EmpleadoCreateView.as_view(),
        name='empleado_add'
    ),
    path(
        'success/', 
        views.SuccessView.as_view(),
        name='correcto',
    ),
    path(
        'update-empleado/<pk>/', 
        views.EmpleadoUpdateView.as_view(),
        name='modificar_empleado',
    ),
    path(
        'delete-empleado/<pk>/', 
        views.EmpleadoDeleteView.as_view(),
        name='eliminar_empleado',
    ),
]

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

empleado/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.home.urls')),
    path('', include('applications.departamento.urls')),
    path('', include('applications.persona.urls')),
] 

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/persona/models.py
from django.db import models
from applications.departamento.models import Departamento
from ckeditor.fields import RichTextField

class Habilidades(models.Model):
    habilidad = models.CharField(max_length=50)
    
    
    # class Meta:
        # verbose_name='Mi departamento'
        # verbose_name_plural='Areas de la empresa'

    def __str__(self):
        return str(self.id)+'-'+self.habilidad    
            
class Empleado(models.Model):
    JOB_CHOICES=(
        ('0','Contador'),
        ('1','Administrador'),
        ('2','Economista'),
        ('3','Otro'),
    )
    first_name = models.CharField('Nombres', max_length=60)
    last_name = models.CharField('Apellidos', max_length=60)
    
    full_name = models.CharField(
        'Nombres Completos',
        max_length=120,
        blank=True
    )
    
    job = models.CharField('Trabajo', max_length=1,choices=JOB_CHOICES)
    departamento=models.ForeignKey(Departamento, on_delete=models.CASCADE)
    
    # este anda
    #avatar=models.ImageField(upload_to='fotos', blank=True, null=True)
    avatar=models.ImageField(upload_to='empleado', blank=True, null=True)
    habilidades = models.ManyToManyField(Habilidades)
    hoja_vida= RichTextField() 
    
    class Meta:
        # verbose_name='Mi departamento'
        # verbose_name_plural='Areas de la empresa'
        ordering=['-id','first_name','last_name']
        # unique_together=('name','shor_name')
        

    
    def __str__(self):
        return str(self.id)+'-'+self.first_name+'-'+self.last_name
    

applications/persona/forms.py
from django import forms

from .models import Empleado

class EmpleadoForm(forms.ModelForm):
    """Form definition for Empleado."""

    class Meta:
        """Meta definition for Empleadoform."""

        model = Empleado
        fields = (
            'first_name',
            'last_name',
            'job',
            'departamento',
            'avatar',
            'habilidades',
            )
        # si queremos personalizar utilizamos el elemento widget
        widgets = {
            'habilidades': forms.CheckboxSelectMultiple()    
        }

applications/persona/views.py
from django.shortcuts import render

from django.urls import reverse_lazy

from django.views.generic import (
    TemplateView,
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)

# llamo todos los modelo que usare en las vistas
from .models import Empleado
# llamo los forms
from .forms import EmpleadoForm

class InicioView(TemplateView):
    template_name="inicio.html"

# listar todos los empleados de la empresa

class ListAllEmpleados(ListView):
    #model = Empleado
    template_name = "persona/list_all.html"
    paginate_by=4
    ordering='first_name'
    context_object_name = 'empleados'

    def get_queryset(self):
        palabra_clave = self.request.GET.get("kword",'')
        lista = Empleado.objects.filter(
            first_name__icontains=palabra_clave
            )
        return lista 


# administrar crud

class ListEmpleadosAdmin(ListView):
    #model = Empleado
    template_name = "persona/lista_empleados.html"
    paginate_by=6
    ordering='first_name'
    context_object_name = 'empleados'
    model = Empleado


# listar todos los empleados de la empresa que pertenecen a un area

class ListByAreaEmpleado(ListView):
    template_name = "persona/list_by_area.html"
    context_object_name='empleados'

    def get_queryset(self):
        area=self.kwargs['shorname']
        lista=Empleado.objects.filter(
            departamento__shor_name=area
        )
        return lista

# listar empleados por palabra clave

class ListEmpleadoByKword(ListView):
    template_name = "persona/by_kword.html"
    context_object_name='empleados'

    def get_queryset(self):
        # desde get formulario
        palabra_clave=self.request.GET.get("kword", '')
        lista=Empleado.objects.filter(
             first_name=palabra_clave
        )
        return lista

# listar habilidades de un  empleado

class ListHabilidadesEmpleado(ListView):
    template_name = "persona/habilidades.html"
    context_object_name='habilidades'
    def get_queryset(self):
        # selecciono el registro numero 2 de empleado desde tabla
        empleado=Empleado.objects.get(id=2)
        return empleado.habilidades.all()
    
class EmpleadoDetailView(DetailView):
    model = Empleado
    template_name = "persona/detail_empleado.html"
    def get_context_data(self, **kwargs):
        context=super(EmpleadoDetailView, self).get_context_data(**kwargs)
        context['titulo']='Empleado del mes'
        return context
    

class SuccessView(TemplateView):
    template_name = "persona/success.html"

class EmpleadoCreateView(CreateView):
    model = Empleado
    template_name = "persona/add.html"
    form_class = EmpleadoForm
    success_url=reverse_lazy('persona_app:empleados_admin')
    #success_url=reverse_lazy('persona_app:correcto')

    def form_valid(self, form):

        # logica de validacion
        empleado=form.save(commit=False)

        empleado.full_name=empleado.first_name+' '+empleado.last_name

        empleado.save()

        return super(EmpleadoCreateView, self).form_valid(form)


class EmpleadoUpdateView(UpdateView):
    
    model = Empleado
    
    template_name ="persona/update.html"
    
    fields=['first_name','last_name','job','departamento','habilidades']
    
    success_url=reverse_lazy('persona_app:empleados_admin')

    def post(self, request, *args, **kwargs):
        
        self.object = self.get_object()
        
        return super().post(request, *args, **kwargs)
    
    def form_valid(self, form):

        return super(EmpleadoUpdateView, self).form_valid(form)

class EmpleadoDeleteView(DeleteView):
    
    model = Empleado
    
    template_name ="persona/delete.html"
    
    success_url=reverse_lazy('persona_app:empleados_admin')

 

templates/persona/add.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    Registrar empleado
{% endblock title %}



{% block content %}
{% include 'includes/header.html' %}

<div class="grid-container">
    <dif class="grid-x">
        <h1 class="cell">
            Registrar Empleado
            </h1>
            <div class="cell">
                <form action="" class="grid-x grid-margin-x" enctype="multipart/form-data" method="post"> {% csrf_token %}

                    <div class="cell large-6">
                        <label>Nombres:
                          {{form.first_name}}
                        </label>
                     </div>
                    <div class="cell large-6">
                        <label>Apellidos:
                          {{form.last_name}}
                        </label>
                     </div>
                    <div class="cell large-6">
                        <label>Trabajo:
                          {{form.job}}
                        </label>
                     </div>
                    <div class="cell large-6">
                        <label>Área:
                          {{form.departamento}}
                        </label>
                     </div>
                    <div class="cell large-6">
                        <label>Habilidades extra:
                          {{form.habilidades}}
                        </label>
                     </div>
                    <div class="cell large-6">
                        <label>Foto:
                          {{form.avatar}}
                        </label>
                     </div>
                    <div class="cell">
                        <button type="submit" class="submit success button">Guardar</button>
                    </div>
                </form>
            
            </div>
        </dif>
    </div>
    
{% endblock content %}
    

templates/persona/by_kword.html
<h1>Buscar empleados por palabra clave</h1>
<head>
    <!-- Compressed CSS -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/foundation-sites@6.8.1/dist/css/foundation.min.css" crossorigin="anonymous">

<!-- Compressed JavaScript -->
<script src="https://cdn.jsdelivr.net/npm/foundation-sites@6.8.1/dist/js/foundation.min.js" crossorigin="anonymous"></script>

</head>
<form action="" class="get"> {% csrf_token %}
    
    <input type="text" id="kword" name="kword" placeholder="Ingrese su texto aquí...">
    
    <button type="submit">Buscar</button>


</form>

<h3>Listado de resultados</h3>

<ul>
    {% for e in empleados %}
        <li>{{e}}</li>
    {% endfor %}
</ul>

templates/persona/delete.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    Eliminar empleado
{% endblock title %}

{% block content %}
    {% include 'includes/header.html' %}

    <div class="grid-container">
        <dif class="grid-x">
            <h1 class="cell">
                Eliminar Empleado
            </h1>
            <div class="cell">
                <form action="" class="grid-x grid-margin-x" method="post"> {% csrf_token %}

                    <div class="callout alert">
                        <h5>Confirme la eliminación de {{object.first_name}} {{object.last_name}}</h5>
                        <button type="submit" class="submit success button">Confirmar</button>
                      </div>

                </form>
            
            </div>
        </dif>
    </div>
    
{% endblock content %}
    



    

templates/persona/detail_empleado.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    Datos de {{empleado.first_name}} {{empleado.last_name}}
{% endblock title %}

{% block content %}
    {% include 'includes/header.html' %}

    <div class="grid-container">
        <dif class="grid-x grid-margin-x align-center">
            
            <div class="cell large-4 card">
                <div class="card" style="width: 300px; margin-top: 10px;">
                    <div class="card-divider">
                      {{empleado.get_job_display}}
                    </div>
                    
                    {% if empleado.avatar %}

                        <img src="{{empleado.avatar.url}}">
                        
                    {% else %}

                        <img src="{% static 'img/03.jpg' %}">
                        
                    {% endif %}
                        
                    <div class="card-section">
                      <h4>{{empleado.first_name}} {{empleado.last_name}}</h4>
                      <p>{{empleado.departamento.shor_name}}</p>
                      <p><span class="label">Habilidades:</span></p>
                      <ul class='vertical menu'>
                        
                        {% for h in empleado.habilidades.all %}
                            <li>
                                {{h.habilidad}}
                            </li>
                        {% endfor %}
                            

                      </ul>
                    </div>

                </div>
            </div>
        </dif>
    </div>
    
{% endblock content %}

templates/persona/habilidades.html
<h1>Habilidades del empleado</h1>
<ul>
    {% for h in habilidades %}
        <li>{{h}}</li>
    {% endfor %}
</ul>

templates/persona/list_all.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    Lista de todos los empleados
{% endblock title %}


{% block content %}
    
    {% include 'includes/header.html' %}
    
    <div class="grid-container">

        <div class="grid-x">
            <h1 class="cell">Lista Empleados</h1>
            <form  class="cell grid-x grid-margin-x" method="GET"> {% csrf_token %}
               <div class="cell large-7">
                    <input type="text" name="kword" id="kword"  placeholder="Buscar empleado">
               </div>
               <div class="cell large-2">
                    <button type="submit" class="success button">Buscar</button>
               </div>
            </form>
            <div class="cell">

                <table>
                    <thead>
                      <tr>
                        <th>ID</th>
                        <th>NOMBRE(S)</th>
                        <th>APELLIDO(S)</th>
                        <th>DEPARTAMENTO</th>
                        <th>ACCION</th>
                      </tr>
                    </thead>
                    <tbody>
                      {% for e in empleados %}
                        <tr>
                            <td><p style="text-align: right;">{{e.id}}</p></td>
                            <td><p>{{e.first_name}}</p></td>
                            <td><p>{{e.last_name}}</p></td>
                            <td><p>{{e.departamento.shor_name}}</p></td>
                            <td><p>
                                    <a class="button warning" href="{% url 'persona_app:empleado_detail' e.id %}">Ver</a>
                                </p>
                            </td>
                        </tr>
                      {% endfor %}
                     </tbody>
                </table>    
            </div>

            <!-- paginacion -->

            <div class="cell">
                
                {% if is_paginated %}

                    <nav aria-label="Pagination">
                        <ul class="pagination">
                            
                            {% if page_obj.has_previous  %}
                                <li class="pagination-previous"><a href="?page={{page_obj.previous_page_number}}">Anterior</a></li>
                            {% endif %}
                            
                            
                            {% for pagina in paginator.page_range %}


                                    {% if pagina == page_obj.number  %} 
                                        <li class="current"><a href="?page={{pagina}}" aria-label="Page 2">{{pagina}}</a></li>
                                    {% else %}
                                        <li class=""><a href="?page={{pagina}}" aria-label="Page 2">{{pagina}}</a></li>
                                    {% endif %}
                                     

                                
                            {% endfor %}
                            
                            {% if page_obj.has_next  %}
                                <li class="pagination-next"><a href="?page={{page_obj.next_page_number}}">Próxima</a></li>
                            {% endif %}
                            
                       </ul>
                    </nav>
                
                {% endif %}

            </div>
        </div>

    </div>

{% endblock content %}
        

templates/persona/list_by_area.html
{% extends "base.html" %}
{% load static %}


{% block title %}
Lista de empleados por departamento
{% endblock title %}


{% block content %}

{% include 'includes/header.html' %}

<div class="grid-container">
    
    <div class="grid-x">
        <h1 class="cell">Empleados del Departamento Empleados</h1>

        <div class="cell">

            <table>
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>NOMBRE(S)</th>
                        <th>APELLIDO(S)</th>
                        <th>ÁREA</th>
                        <th>DEPARTAMENTO</th>
                    </tr>
                </thead>
                <tbody>
                    {% for e in empleados %}
                    <tr>
                        <td><p style="text-align: right;">{{e.id}}</p></td>
                        <td><p>{{e.first_name}}</p></td>
                        <td><p>{{e.last_name}}</p></td>
                        <td><p>{{e.departamento.name}}</p></td>
                        <td><p>{{e.departamento.shor_name}}</p></td>
                    </tr>
                    {% endfor %}
                </tbody>
                </table>    
            </div>
        </div>
    </div>
{% endblock content %}
    

templates/persona/lista_empleados.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    Lista de todos los empleados
{% endblock title %}


{% block content %}
    
    {% include 'includes/header.html' %}
    
    <div class="grid-container">

        <div class="grid-x">
            <h1 class="cell">Administrar Empleados</h1>

            <div class="cell">

                <table>
                    <thead>
                      <tr>
                        <th>ID</th>
                        <th>NOMBRE(S)</th>
                        <th>APELLIDO(S)</th>
                        <th>DEPARTAMENTO</th>
                        <th>ACCION</th>
                      </tr>
                    </thead>
                    <tbody>
                      {% for e in empleados %}
                        <tr>
                            <td><p style="text-align: right;">{{e.id}}</p></td>
                            <td><p>{{e.first_name}}</p></td>
                            <td><p>{{e.last_name}}</p></td>
                            <td><p>{{e.departamento.shor_name}}</p></td>
                            <td>
                                    <a class="button success" href="{% url 'persona_app:modificar_empleado' e.id %}">Editar</a>
                                    <a class="button alert" href="{% url 'persona_app:eliminar_empleado' e.id %}">Eliminar</a>

                            </td>
                        </tr>
                      {% endfor %}
                     </tbody>
                </table>    
            </div>

            <!-- paginacion -->

            <div class="cell">
                
                {% if is_paginated %}

                    <nav aria-label="Pagination">
                        <ul class="pagination">
                            
                            {% if page_obj.has_previous  %}
                                <li class="pagination-previous"><a href="?page={{page_obj.previous_page_number}}">Anterior</a></li>
                            {% endif %}
                            
                            
                            {% for pagina in paginator.page_range %}


                                    {% if pagina == page_obj.number  %} 
                                        <li class="current"><a href="?page={{pagina}}" aria-label="Page 2">{{pagina}}</a></li>
                                    {% else %}
                                        <li class=""><a href="?page={{pagina}}" aria-label="Page 2">{{pagina}}</a></li>
                                    {% endif %}
                                     

                                
                            {% endfor %}
                            
                            {% if page_obj.has_next  %}
                                <li class="pagination-next"><a href="?page={{page_obj.next_page_number}}">Próxima</a></li>
                            {% endif %}
                            
                       </ul>
                    </nav>
                
                {% endif %}

            </div>
        </div>

    </div>

{% endblock content %}
        

templates/persona/success.html
<h1>Correcto</h1>

templates/persona/update.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    Editar empleado
{% endblock title %}



{% block content %}
    {% include 'includes/header.html' %}

    <div class="grid-container">
        <dif class="grid-x">
            <h1 class="cell">
                Modificar Empleado
            </h1>
            <div class="cell">
                <form action="" class="grid-x grid-margin-x" method="post"> {% csrf_token %}

                    <div class="cell large-6">
                        <label>Nombres:
                          {{form.first_name}}
                        </label>
                     </div>
                    <div class="cell large-6">
                        <label>Apellidos:
                          {{form.last_name}}
                        </label>
                     </div>
                    <div class="cell large-6">
                        <label>Trabajo:
                          {{form.job}}
                        </label>
                     </div>
                    <div class="cell large-6">
                        <label>Área:
                          {{form.departamento}}
                        </label>
                     </div>
                    <div class="cell large-6">
                        <label>Habilidades extra:
                          {{form.habilidades}}
                        </label>
                     </div>
                    <div class="cell">
                        <button type="submit" class="submit success button">Guardar</button>
                     </div>
                </form>
            
            </div>
        </dif>
    </div>
    
{% endblock content %}
    