applications/departamento/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'departamento_app'

urlpatterns = [
    path('departamento-lista',
         views.DepartamentoListView.as_view(),
         name='departamento_list'
    ),
    path('new-departamento',
         views.NewDepartamentoView.as_view(),
         name='nuevo_departamento'
    ),

    
]

applications/persona/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name="persona_app"

urlpatterns = [
    path(
        '', 
        views.InicioView.as_view(),
        name='inicio'
    ),
    path(
        'listar-todo-empleados/', 
        views.ListAllEmpleados.as_view(),
        name='empleados_all'
    ),
    path(
        'lista-by-area/<shorname>/', 
        views.ListByAreaEmpleado.as_view(),
        name='empleados_area'
    ),
    path(
        'lista-empleados-admin/', 
        views.ListEmpleadosAdmin.as_view(),
        name='empleados_admin'
    ),
    path(
        'buscar-empleado/', 
        views.ListEmpleadoByKword.as_view(),
        name='lista_by_area'
    ),
    path(
        'lista-habilidades-empleado/', 
        views.ListHabilidadesEmpleado.as_view(),
        name='lista_habilidades_empleado'
    ),
    path(
        'ver-empleado/<pk>/', 
        views.EmpleadoDetailView.as_view(),
        name='empleado_detail'
    ),
    path(
        'add-empleado/', 
        views.EmpleadoCreateView.as_view(),
        name='empleado_add'
    ),
    path(
        'success/', 
        views.SuccessView.as_view(),
        name='correcto',
    ),
    path(
        'update-empleado/<pk>/', 
        views.EmpleadoUpdateView.as_view(),
        name='modificar_empleado',
    ),
    path(
        'delete-empleado/<pk>/', 
        views.EmpleadoDeleteView.as_view(),
        name='eliminar_empleado',
    ),
]

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

empleado/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.home.urls')),
    path('', include('applications.departamento.urls')),
    path('', include('applications.persona.urls')),
] 

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/header.html
{% load static %}

<div class="top-bar">
    <div class="top-bar-left">
      <ul class="dropdown menu" data-dropdown-menu>
        <li class="menu-text">Empleados</li>
        <li><a href="{% url 'persona_app:empleados_all' %}">Listar</a></li>
        <li><a href="{% url 'departamento_app:departamento_list' %}">Departamentos</a></li>
        <li><a href="{% url 'persona_app:empleados_admin' %}">Administrar</a></li>
        <li><a href="{% url 'departamento_app:nuevo_departamento' %}">Nuevo Departamento</a></li>
      </ul>
    </div>
    <div class="top-bar-right">
      <ul class="menu">
        <li><input type="search" placeholder="Buscar Empleado"></li>
        <li><a  href="{% url 'persona_app:empleado_add' %}" class="button">Registrar Nuevo</a></li>
      </ul>
    </div>
  </div>