applications/departamento/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'departamento_app'

urlpatterns = [
    path('departamento-lista',
         views.DepartamentoListView.as_view(),
         name='departamento_list'
    ),
    path('new-departamento',
         views.NewDepartamentoView.as_view(),
         name='nuevo_departamento'
    ),

    
]

applications/persona/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name="persona_app"

urlpatterns = [
    path(
        '', 
        views.InicioView.as_view(),
        name='inicio'
    ),
    path(
        'listar-todo-empleados/', 
        views.ListAllEmpleados.as_view(),
        name='empleados_all'
    ),
    path(
        'lista-by-area/<shorname>/', 
        views.ListByAreaEmpleado.as_view(),
        name='empleados_area'
    ),
    path(
        'lista-empleados-admin/', 
        views.ListEmpleadosAdmin.as_view(),
        name='empleados_admin'
    ),
    path(
        'buscar-empleado/', 
        views.ListEmpleadoByKword.as_view(),
        name='lista_by_area'
    ),
    path(
        'lista-habilidades-empleado/', 
        views.ListHabilidadesEmpleado.as_view(),
        name='lista_habilidades_empleado'
    ),
    path(
        'ver-empleado/<pk>/', 
        views.EmpleadoDetailView.as_view(),
        name='empleado_detail'
    ),
    path(
        'add-empleado/', 
        views.EmpleadoCreateView.as_view(),
        name='empleado_add'
    ),
    path(
        'success/', 
        views.SuccessView.as_view(),
        name='correcto',
    ),
    path(
        'update-empleado/<pk>/', 
        views.EmpleadoUpdateView.as_view(),
        name='modificar_empleado',
    ),
    path(
        'delete-empleado/<pk>/', 
        views.EmpleadoDeleteView.as_view(),
        name='eliminar_empleado',
    ),
]

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

empleado/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.home.urls')),
    path('', include('applications.departamento.urls')),
    path('', include('applications.persona.urls')),
] 

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/departamento/models.py
from django.db import models

class Departamento(models.Model):
    name = models.CharField('Nombre', max_length=50)
    shor_name = models.CharField('Nombre Corto', max_length=20)
    anulate = models.BooleanField('Anulado', default=False)
    
    class Meta:
        # verbose_name='Mi departamento'
        # verbose_name_plural='Areas de la empresa'
        ordering=['name']
        # unique_together=('name','shor_name')
    
    def __str__(self):
        return str(self.id)+'-'+self.name+'-'+self.shor_name
    
    

applications/departamento/forms.py
from django import forms

class NewDepartamentoForm(forms.Form):
    nombre = forms.CharField(max_length=50)
    apellidos = forms.CharField(max_length=50)
    departamento = forms.CharField(max_length=50)
    shorname = forms.CharField(max_length=20)
    

applications/departamento/views.py
from django.shortcuts import render
from django.views.generic import ListView
from django.views.generic.edit import FormView
from applications.persona.models import Empleado
from .models import Departamento
from .forms import NewDepartamentoForm

class DepartamentoListView(ListView):
    model = Departamento
    template_name='departamento/lista.html'
    context_object_name='departamentos'


class NewDepartamentoView(FormView):
    template_name='departamento/new_departamento.html'
    form_class=NewDepartamentoForm
    success_url='/'
    
    def form_valid(self, form):
        
 
        depa = Departamento(
             name=form.cleaned_data['departamento'],
             shor_name=form.cleaned_data['shorname'],
        )
        depa.save()
        nombre = form.cleaned_data['nombre']
        apellido=form.cleaned_data['apellidos']
        Empleado.objects.create(
           first_name=nombre,
            last_name=apellido,
            job='1',
            departamento=depa
        )
        return super(NewDepartamentoView, self).form_valid(form)
    
    

templates/departamento/lista.html
{% extends "base.html" %}

{% block title %}
    Lista departamentos
{% endblock title %}


{% block content %}
{% include 'includes/header.html' %}

<div class="grid-container">
    
    <div class="grid-x">
        <h1 class="cell">Lista Departamentos</h1>
        <div class="cell">
            
            <table>
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>DEPARTAMENTOS</th>
                        <th>NOMBRE</th>
                        <th>ACCION</th>
                    </tr>
                </thead>
                <tbody>
                    {% for departamento in departamentos %}
                                <tr>
                                    <td><p style="text-align: right;">{{departamento.id}}</p></td>
                                    <td><p>{{departamento.name}}</p></td>
                                    <td><p>{{departamento.shor_name}}</p></td>
                                    <td><p>
                                            <a class="button warning" href="{% url 'persona_app:empleados_area' departamento.shor_name %}">Ver Empleados</a>
                                        </p>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>    
                </div>
{% endblock content %}
    
    

templates/departamento/new_departamento.html
{% extends 'base.html' %}


{% block title %}
    Registrar Departamento
{% endblock title %}
    

{% block content %}
    {% include 'includes/header.html' %}

    <div class="grid-container">
        <div class="grid-x">
            <h1 cell>Registrar Departamento</h1>
            <form action="" class="cell callout grid-x grid-margin-x" method="post">{% csrf_token %}
                <div class="cell medium-6">
                    <label for="">Nombres:
                        {{form.nombre}}
                    </label>
                </div>
                <div class="cell medium-6">
                    <label for="">Apellidos:
                        {{form.apellidos}}
                    </label>
                </div>
                <div class="cell medium-6">
                    <label for="">Departamento:
                        {{form.departamento}}
                    </label>
                </div>
                <div class="cell medium-6">
                    <label for="">Nombre Corto:
                        {{form.shorname}}
                    </label>
                </div>
                <div class="cell medium-12">
                        <button type="submit" class="button">Guardar</button>
                </div>
            </form>
            
        </div>
    </div>
    
{% endblock content %}
    














<form action="" class="post">{% csrf_token %}
    <h3>Datos del empleado</h3>

    <p>
       Nombres: {{form.nombre}}
    </p>
    <p>
       Apellidos: {{form.apellidos}}
    </p>

    <h3>Datos del departamento</h3>

    <p>
        Departamento: {{form.departamento}}
    </p>
    <p>
        Nombre Corto: {{form.shorname}}
    </p>
    <button type="submit">Guardar</button>
</form>